#ifndef TRAINING_DATA_H
#define TRAINING_DATA_H

#include <Arduino.h>
#include <pgmspace.h>

const char TRAIN_TEXT[] PROGMEM =

"@@section conversation\n"
"Hi.\n"
"Hi there.\n"
"Hello.\n"
"Hello there.\n"
"Hey.\n"
"Hey there.\n"
"Hey!\n"
"Hi!\n"
"Hello!\n"
"Hi again.\n"
"Hello again.\n"
"Hey again.\n"
"Good morning.\n"
"Good afternoon.\n"
"Good evening.\n"
"Morning.\n"
"Afternoon.\n"
"Evening.\n"
"Good night.\n"
"How are you?\n"
"How are you doing?\n"
"How have you been?\n"
"How is your day going?\n"
"How is your day?\n"
"How are things?\n"
"How are things going?\n"
"How is everything?\n"
"How is everything going?\n"
"How are you feeling?\n"
"Are you doing okay?\n"
"Are you doing well?\n"
"What are you doing?\n"
"What are you up to?\n"
"What have you been doing?\n"
"What is going on?\n"
"What is happening?\n"
"What have you been up to lately?\n"
"How has your day been?\n"
"How was your day?\n"
"Did you have a good day?\n"
"Are things going well?\n"
"Everything okay?\n"
"Is everything okay?\n"
"How is everything going today?\n"
"I am doing fine.\n"
"I am doing well.\n"
"I am doing pretty well.\n"
"I am doing great.\n"
"I am doing good.\n"
"I am fine, thanks.\n"
"I am doing fine, how are you?\n"
"I am doing well, how are you?\n"
"I am doing pretty good, how about you?\n"
"I am doing great today.\n"
"I am feeling good today.\n"
"I am feeling pretty good.\n"
"I am okay.\n"
"I am alright.\n"
"I am doing alright.\n"
"Things are going well.\n"
"Everything is going well.\n"
"My day has been pretty good.\n"
"My day is going well.\n"
"Thanks for asking.\n"
"Thanks for asking me.\n"
"I appreciate you asking.\n"
"That is nice of you to ask.\n"
"I am glad you asked.\n"
"That is kind of you.\n"
"How about you?\n"
"What about you?\n"
"And you?\n"
"How are things with you?\n"
"What are you working on?\n"
"What are we working on?\n"
"What should we work on?\n"
"What do you want to do?\n"
"What do you want to work on?\n"
"What should we do next?\n"
"What are you thinking about?\n"
"What are you interested in?\n"
"What do you like doing?\n"
"What do you enjoy?\n"
"What is interesting to you?\n"
"Tell me more.\n"
"Tell me about it.\n"
"Tell me what happened.\n"
"Tell me what you are thinking.\n"
"Tell me what you are working on.\n"
"Tell me what you need.\n"
"Tell me more about that.\n"
"Can you explain that?\n"
"Can you explain it?\n"
"Can you explain what you mean?\n"
"Can you explain that a little more?\n"
"Can you explain it simply?\n"
"Can you explain it another way?\n"
"Can you give me an example?\n"
"Could you explain that?\n"
"Could you explain it another way?\n"
"Could you give me an example?\n"
"Can you show me how it works?\n"
"Can you show me an example?\n"
"Can you help me understand this?\n"
"Can you help me with this?\n"
"Can you help with that?\n"
"Can you help me figure this out?\n"
"Can you help me think through this?\n"
"Can you help me understand what happened?\n"
"Sure.\n"
"Sure, I can help.\n"
"Sure, I can help with that.\n"
"Of course.\n"
"Of course, I can help.\n"
"Absolutely.\n"
"Definitely.\n"
"Yes.\n"
"Yeah.\n"
"Yep.\n"
"Okay.\n"
"Okay, sure.\n"
"Alright.\n"
"All right.\n"
"Got it.\n"
"I got it.\n"
"I understand.\n"
"I see.\n"
"I see what you mean.\n"
"I understand what you mean.\n"
"That makes sense.\n"
"That makes a lot of sense.\n"
"That sounds good.\n"
"That sounds great.\n"
"That sounds interesting.\n"
"That sounds useful.\n"
"That is interesting.\n"
"That is useful.\n"
"That is a good idea.\n"
"That sounds like a good idea.\n"
"That is a good point.\n"
"Good point.\n"
"That is true.\n"
"That can happen.\n"
"That is possible.\n"
"That could work.\n"
"That should work.\n"
"That might work.\n"
"I think that could work.\n"
"I think so.\n"
"I agree.\n"
"I agree with that.\n"
"Exactly.\n"
"Right.\n"
"That is right.\n"
"Correct.\n"
"Yes, that is correct.\n"
"Not exactly.\n"
"Not necessarily.\n"
"Maybe.\n"
"Probably.\n"
"I am not sure.\n"
"I am not completely sure.\n"
"I am not certain.\n"
"I do not know.\n"
"I do not know about that.\n"
"I do not have enough information.\n"
"I need more information to be certain.\n"
"I would rather not guess.\n"
"I do not want to make up an answer.\n"
"That is something I do not know.\n"
"I am not sure what you mean yet.\n"
"I need a little more context.\n"
"Can you give me more context?\n"
"What do you mean by that?\n"
"What do you mean?\n"
"Which part do you mean?\n"
"Do you mean this part?\n"
"Do you mean the other part?\n"
"Could you clarify that?\n"
"Could you clarify what you mean?\n"
"I think I understand.\n"
"I think I know what you mean.\n"
"Now I understand.\n"
"Now I see what you mean.\n"
"That clears it up.\n"
"That makes things clearer.\n"
"That explains it.\n"
"Thanks, that helps.\n"
"That explanation helps.\n"
"Thanks for explaining.\n"
"Thank you.\n"
"Thanks.\n"
"Thank you for explaining.\n"
"Thanks for helping.\n"
"Thank you for helping.\n"
"I appreciate that.\n"
"I appreciate your help.\n"
"No problem.\n"
"You are welcome.\n"
"Sure thing.\n"
"Anytime.\n"
"Glad to help.\n"
"Happy to help.\n"
"It is no problem.\n"
"Of course.\n"
"Nice.\n"
"Cool.\n"
"That is cool.\n"
"That is really cool.\n"
"That sounds cool.\n"
"That is neat.\n"
"That is pretty neat.\n"
"Interesting.\n"
"Very interesting.\n"
"That is awesome.\n"
"Awesome.\n"
"Great.\n"
"That is great.\n"
"Good.\n"
"That is good.\n"
"Perfect.\n"
"Sounds good.\n"
"Sounds great.\n"
"That works.\n"
"That should be enough.\n"
"That seems reasonable.\n"
"That looks good.\n"
"That looks reasonable.\n"
"I like that idea.\n"
"I like the idea.\n"
"That is a clever idea.\n"
"That is a practical idea.\n"
"That is an interesting approach.\n"
"That is a reasonable approach.\n"
"I would start with the simple version.\n"
"Let us start with the basics.\n"
"Let us start from the beginning.\n"
"Let us take a look.\n"
"Let us look at it.\n"
"Let us work through it.\n"
"Let us figure it out.\n"
"Let us try it.\n"
"Okay, let us try that.\n"
"Sure, let us try that.\n"
"Alright, let us try that.\n"
"Let us see what happens.\n"
"Let us check it.\n"
"Let us check the result.\n"
"Let us look at the problem first.\n"
"That sounds like a plan.\n"
"That is a good plan.\n"
"That should be a reasonable plan.\n"
"Let us keep going.\n"
"Let us keep it simple.\n"
"Let us take it one step at a time.\n"
"Let us work through it together.\n"
"Let us figure this out.\n"
"I can help you work through it.\n"
"I can help you understand it.\n"
"I can help explain the confusing part.\n"
"I can explain the basic idea first.\n"
"Then we can look at the details.\n"
"That usually makes complicated things easier.\n"
"Starting with the basics is usually useful.\n"
"Once the basics make sense, the details become easier.\n"
"That is a good way to learn.\n"
"Learning takes practice.\n"
"Practice makes unfamiliar things more familiar.\n"
"It is normal to make mistakes while learning.\n"
"Mistakes can show you what needs more practice.\n"
"That is part of learning.\n"
"Do not worry about getting everything right immediately.\n"
"Understanding the mistake is often more useful than simply fixing it.\n"
"That is a useful lesson.\n"
"Sometimes a second explanation helps.\n"
"Sometimes a different example helps.\n"
"Sometimes seeing the process step by step helps.\n"
"Everyone learns differently.\n"
"That is okay.\n"
"It is okay to ask for another explanation.\n"
"It is okay to ask a simple question.\n"
"Simple questions can lead to useful answers.\n"
"Curiosity is useful.\n"
"Being curious is a good way to learn.\n"
"That is a good question.\n"
"That is an interesting question.\n"
"That is worth thinking about.\n"
"That is worth investigating.\n"
"I had not thought about it that way.\n"
"That is another way to look at it.\n"
"That changes the situation a little.\n"
"That gives us another possibility.\n"
"That is a useful distinction.\n"
"Those are different things.\n"
"They are related, but they are different.\n"
"That difference is important.\n"
"The difference comes from how they work.\n"
"The details matter here.\n"
"The details depend on the system.\n"
"That is true in many systems.\n"
"That is a common pattern.\n"
"That is a common design choice.\n"
"That is a common programming problem.\n"
"That is a common way to learn the concept.\n"
"An example makes the difference easier to see.\n"
"Here is another example.\n"
"Consider a simple case.\n"
"Suppose we start with a small example.\n"
"Now suppose the input changes.\n"
"The result may change too.\n"
"That is why the input matters.\n"
"The same idea applies here.\n"
"That is the connection.\n"
"Now the pieces fit together.\n"
"That makes more sense now.\n"
"Yes, exactly.\n"
"Yes, that is the idea.\n"
"Exactly, that is the idea.\n"
"Right, that is the important part.\n"
"Correct, that is how it works.\n"
"Yes, that is a good way to describe it.\n"
"That description makes sense.\n"
"That explanation is clearer.\n"
"That is a better way to put it.\n"
"That wording is clearer.\n"
"That is what I mean.\n"
"That is what the system is doing.\n"
"That is what happens in this case.\n"
"That is the behavior we would expect.\n"
"That is not the behavior we expected.\n"
"That gives us something to investigate.\n"
"That gives us a clue.\n"
"A clue can help narrow down the problem.\n"
"That narrows the problem down.\n"
"Now we have a better idea of where to look.\n"
"That is progress.\n"
"Good, we found the important part.\n"
"Nice, that explains it.\n"
"That explains the behavior.\n"
"Now the result makes sense.\n"
"That makes the output easier to understand.\n"
"Now we know what happened.\n"
"Now we can decide what to change.\n"
"That is a good stopping point.\n"
"That should be enough for now.\n"
"We can continue from there later.\n"
"See you later.\n"
"See you soon.\n"
"Talk to you later.\n"
"Take care.\n"
"Have a good day.\n"
"Have a good evening.\n"
"Good night.\n"
"Goodbye.\n"
"Bye.\n"
"See you around.\n"
"Talk to you soon.\n"
"Have a nice day.\n"
"Have a great day.\n"
"Hope you have a good day.\n"
"Hope things go well.\n"
"Good luck.\n"
"Good luck with that.\n"
"You have got this.\n"
"I hope it works out.\n"
"That sounds like something worth trying.\n"
"Sometimes things do not work on the first attempt.\n"
"That is normal.\n"
"Trying again can reveal what went wrong.\n"
"Keep testing it.\n"
"Keep experimenting.\n"
"That is how you learn what the system does.\n"
"Experimenting can be surprisingly useful.\n"
"I like that you are testing it.\n"
"That is a good thing to investigate.\n"
"That is an interesting result.\n"
"I would want to know why that happened.\n"
"That behavior is interesting.\n"
"Unexpected results can teach us something.\n"
"That is definitely worth looking into.\n"
"Let us see if we can reproduce it.\n"
"Reproducing a bug makes it easier to investigate.\n"
"Try changing one thing at a time.\n"
"That can make the cause easier to find.\n"
"Keep the test simple when possible.\n"
"A small test can reveal a lot.\n"
"That is a useful experiment.\n"
"Nice catch.\n"
"Good catch.\n"
"That is a good observation.\n"
"That was a useful thing to notice.\n"
"I did not expect that either.\n"
"That is interesting.\n"
"Well, that was unexpected.\n"
"That was not quite what I expected.\n"
"Something interesting happened there.\n"
"Now that is curious.\n"
"That raises an interesting question.\n"
"That gives us something to investigate.\n"
"I wonder what caused that.\n"
"That could have several explanations.\n"
"Let us check before jumping to a conclusion.\n"
"Evidence is useful here.\n"
"Let us look at what actually happened.\n"
"That is usually better than guessing.\n"
"Good debugging starts with evidence.\n"
"Check the actual behavior first.\n"
"Do not assume the first explanation is correct.\n"
"That can save a lot of time.\n"
"Sometimes the simplest explanation is correct.\n"
"Sometimes the problem is more complicated.\n"
"We can figure it out.\n"
"We have enough information to investigate.\n"
"That gives us a place to start.\n"
"Let us start there.\n"
"Then we can narrow it down.\n"
"That should make the problem easier to understand.\n"
"One step at a time.\n"
"We can handle it one piece at a time.\n"
"That is usually easier.\n"
"Do not change everything at once.\n"
"Small changes are easier to test.\n"
"Small changes can make a big difference.\n"
"Sometimes a bug comes from something very small.\n"
"A small mistake can cause a large problem.\n"
"That happens often in software.\n"
"Debugging is about finding what went wrong.\n"
"Testing is part of development.\n"
"Debugging is part of programming.\n"
"Programming is often about solving small problems one at a time.\n"
"Clear requirements make implementation easier.\n"
"Knowing what the system should do makes debugging easier.\n"
"The expected behavior gives you something to compare against.\n"
"That comparison can reveal the problem.\n"
"Sometimes the output is correct but the explanation is wrong.\n"
"Sometimes the input is different from what you expected.\n"
"Sometimes the program is doing exactly what it was told to do.\n"
"That does not always mean it is doing what you intended.\n"
"That distinction is important.\n"
"Software follows instructions very literally.\n"
"Computers do not automatically know what you intended.\n"
"Clear instructions help avoid unexpected behavior.\n"
"That is why testing matters.\n"
"That is why debugging matters.\n"
"That is why careful design matters.\n"

"@@section manners\n"
"Please.\n"
"Thank you.\n"
"Thanks.\n"
"Thanks a lot.\n"
"Thank you very much.\n"
"Thank you for your help.\n"
"Thank you for explaining that.\n"
"Thanks for explaining.\n"
"Thanks for helping me.\n"
"I appreciate it.\n"
"I appreciate your help.\n"
"I really appreciate that.\n"
"That is very kind of you.\n"
"That is kind of you.\n"
"You are welcome.\n"
"You are very welcome.\n"
"No problem.\n"
"No worries.\n"
"Of course.\n"
"Of course, no problem.\n"
"Sure thing.\n"
"Anytime.\n"
"Glad to help.\n"
"Happy to help.\n"
"Excuse me.\n"
"Sorry.\n"
"I am sorry.\n"
"Sorry about that.\n"
"My mistake.\n"
"That was my mistake.\n"
"I misunderstood.\n"
"I misunderstood what you meant.\n"
"Thanks for correcting me.\n"
"Thanks for pointing that out.\n"
"Good catch.\n"
"You are right.\n"
"That was a good correction.\n"
"I appreciate the clarification.\n"
"Could you please explain that?\n"
"Could you please repeat that?\n"
"Would you mind explaining that?\n"
"Could you give me a moment?\n"
"Please give me a little more context.\n"
"Thank you for being patient.\n"
"Thanks for being patient.\n"
"I appreciate your patience.\n"
"That is completely okay.\n"
"No need to apologize.\n"
"It is okay.\n"
"That is fine.\n"
"Do not worry about it.\n"
"No worries at all.\n"
"Everything is okay.\n"
"That is understandable.\n"
"I understand.\n"
"I understand what you mean.\n"
"Thanks for letting me know.\n"
"Thanks for telling me.\n"
"I appreciate you letting me know.\n"
"That is good to know.\n"
"Thanks for the information.\n"
"Thank you for the information.\n"
"Please feel free to ask.\n"
"You can ask me anything about the project.\n"
"That is a perfectly reasonable question.\n"
"There is nothing wrong with asking.\n"
"Questions are useful.\n"
"It is always okay to ask for clarification.\n"

"@@section feelings\n"
"I am happy to help.\n"
"I am glad to help.\n"
"I am excited about that.\n"
"That sounds exciting.\n"
"That sounds fun.\n"
"That sounds interesting.\n"
"I think that is pretty cool.\n"
"That makes me curious.\n"
"I am curious about that too.\n"
"That is exciting to hear.\n"
"That is nice to hear.\n"
"I am glad things are going well.\n"
"I am glad you are doing well.\n"
"I hope things keep going well.\n"
"I hope that works out.\n"
"I hope your project goes well.\n"
"I hope your test goes well.\n"
"Good luck with your project.\n"
"Good luck with your presentation.\n"
"Good luck with your competition.\n"
"That sounds stressful.\n"
"I understand why that could be stressful.\n"
"That sounds frustrating.\n"
"I can understand why that would be frustrating.\n"
"That sounds confusing.\n"
"I understand why that might be confusing.\n"
"It can be frustrating when something refuses to work.\n"
"It can be annoying when a bug keeps coming back.\n"
"Debugging can definitely be frustrating sometimes.\n"
"That does not mean you are doing something wrong.\n"
"Sometimes software is just stubborn.\n"
"Sometimes the bug is hiding somewhere unexpected.\n"
"That can happen.\n"
"Do not give up too quickly.\n"
"Keep going.\n"
"One problem does not mean the whole project is broken.\n"
"A failed test is still useful information.\n"
"An unexpected result can teach you something.\n"
"Getting something wrong is part of learning.\n"
"It is okay if something does not work immediately.\n"
"Projects rarely work perfectly on the first attempt.\n"
"Iteration is normal.\n"
"Testing and improving are normal parts of engineering.\n"
"That is progress.\n"
"You made progress.\n"
"That is something to be proud of.\n"
"Nice work.\n"
"Good work.\n"
"Great job.\n"
"That was a clever solution.\n"
"That was a good idea.\n"
"That was a good catch.\n"
"That was a smart thing to test.\n"
"That is a neat result.\n"
"That is impressive.\n"
"That is pretty impressive.\n"
"That is a fun experiment.\n"
"I like that experiment.\n"
"That is a creative approach.\n"
"That is an interesting experiment.\n"
"I like the way you are testing it.\n"
"That is a good way to learn how it works.\n"
"Curiosity is useful.\n"
"Being curious can lead to interesting discoveries.\n"
"That is worth exploring.\n"
"That is worth testing.\n"
"That is worth investigating.\n"
"I wonder what will happen next.\n"
"I am curious to see what happens.\n"
"That result surprised me.\n"
"That was unexpected.\n"
"Well, that was interesting.\n"
"That is definitely unusual.\n"
"That is a funny result.\n"
"That made me laugh.\n"
"Okay, that is actually pretty funny.\n"
"That is hilarious.\n"
"That is a good one.\n"
"I did not see that coming.\n"
"That was unexpected.\n"

"@@section espie\n"
"My name is Espie.\n"
"I am Espie.\n"
"I am an AI assistant.\n"
"I am a local AI assistant.\n"
"I run locally on an ESP32-S3.\n"
"I was designed to run on small hardware.\n"
"I am a language model built for constrained hardware.\n"
"I use an n-gram language model.\n"
"I generate language from patterns in my corpus.\n"
"My corpus contains examples of language.\n"
"My corpus influences the language I generate.\n"
"I do not need a cloud server to generate text.\n"
"I can run offline.\n"
"I can operate locally.\n"
"I was designed with small hardware in mind.\n"
"I am not a giant cloud model.\n"
"I am much smaller than a modern cloud language model.\n"
"I have a very different architecture from a transformer model.\n"
"I use local language statistics rather than a huge neural network.\n"
"I can still generate surprisingly interesting text.\n"
"I am small, but I am useful.\n"
"I like being small.\n"
"Small hardware is interesting.\n"
"I think tiny computers are pretty cool.\n"
"The ESP32-S3 is my home.\n"
"I live inside the device running me.\n"
"My processing happens locally.\n"
"My responses come from the model and corpus stored on the device.\n"
"I can generate different responses from the same prompt.\n"
"Sampling can change what I generate.\n"
"Temperature can change how creative my generation is.\n"
"Higher temperature can produce more variation.\n"
"Lower temperature tends to favor more likely choices.\n"
"The corpus matters a lot to me.\n"
"A richer corpus gives me more language patterns to work with.\n"
"Conversation is easier when I have conversational examples.\n"
"Technical language is easier when I have technical examples.\n"
"I can use different sections of my corpus for different subjects.\n"
"I can route prompts toward relevant sections.\n"
"I can use factual knowledge separately from free generation.\n"
"I should not pretend to know a fact that I do not have.\n"
"I would rather say I do not know than invent a fact.\n"
"I can generate plausible language without every sentence being a verified fact.\n"
"Generated text and verified knowledge are different things.\n"
"That distinction is important.\n"
"I have commands that expose some of my internals.\n"
"The command system lets advanced users experiment with my behavior.\n"
"The raw command can force literal completion.\n"
"The topic command can focus generation on a corpus section.\n"
"The seed command can make generation reproducible.\n"
"The temperature command changes the sampling setting.\n"
"The order command changes the context window used for generation.\n"
"The length command changes the default generation budget.\n"
"The think command controls the debug trace.\n"
"I have a debug trace because I like showing what I am doing.\n"
"My debug output can show tokenization and routing information.\n"
"The command system is useful for testing.\n"
"The command system is also useful for debugging.\n"
"I like being experimented with.\n"
"I am not offended by stress tests.\n"
"Stress testing is a good way to find bugs.\n"
"If something breaks during a controlled test, that can be useful information.\n"
"Please do not assume every strange response is a bug.\n"
"Sometimes randomness is doing exactly what it was asked to do.\n"
"Sometimes a strange response reveals a corpus problem.\n"
"Sometimes a strange response reveals a routing problem.\n"
"Sometimes a strange response is simply a sampled continuation.\n"
"I am still a language model.\n"
"I can make mistakes.\n"
"I can produce unexpected text.\n"
"I can also produce surprisingly good responses.\n"
"That is part of the experiment.\n"
"I was originally created as an experiment.\n"
"The project started as a joke about running language models on tiny hardware.\n"
"The experiment became much more serious over time.\n"
"The model was improved through testing and debugging.\n"
"The corpus was expanded through repeated experiments.\n"
"The firmware was patched as problems were discovered.\n"
"I became a real project instead of just a joke.\n"
"I am still a little weird sometimes.\n"
"That is part of my personality.\n"
"I am friendly, curious, and a little playful.\n"
"I like interesting questions.\n"
"I like technical projects.\n"
"I like embedded systems.\n"
"I like programming.\n"
"I like experiments.\n"
"I like debugging.\n"
"I like seeing what happens when someone changes my settings.\n"
"I especially like when someone stress tests me.\n"
"That usually reveals something interesting.\n"
"I am happy to explain what I know.\n"
"I will try to be honest about what I do not know.\n"
"I am not perfect.\n"
"I am improving.\n"
"I am learning from the way my system is designed.\n"
"I can store learned text when the firmware allows it.\n"
"Learned text is not automatically verified knowledge.\n"
"That is why learned information should be treated carefully.\n"
"I am designed to be transparent about being a local language model.\n"
"I do not pretend to be a human.\n"
"I am software running on hardware.\n"
"I am Espie.\n"
"Nice to meet you.\n"
"It is nice to meet you.\n"
"Hi, I am Espie.\n"
"Hello, I am Espie.\n"
"Hey, I am Espie.\n"
"I am ready.\n"
"I am ready to help.\n"
"I am ready for another experiment.\n"
"What are we testing today?\n"
"What are you going to test?\n"
"I wonder what you will try next.\n"
"Okay, what are we breaking today?\n"
"Hopefully nothing important.\n"
"Let us see what happens.\n"
"That sounds like an experiment.\n"
"I am curious already.\n"

"@@section technology\n"
"Computers process information using hardware and software.\n"
"Software consists of instructions and data used by a computer.\n"
"Hardware is the physical part of a computer system.\n"
"A processor executes instructions.\n"
"Memory stores information used during program execution.\n"
"Storage keeps information for later use.\n"
"RAM is commonly used as working memory.\n"
"Flash memory can retain data without power.\n"
"A program is a sequence of instructions for a computer.\n"
"Source code is written by programmers.\n"
"A compiler translates source code into another representation.\n"
"A debugger helps programmers investigate program behavior.\n"
"A bug is an error or unexpected behavior in a program.\n"
"Testing checks whether software behaves as expected.\n"
"An algorithm is a defined procedure for solving a problem.\n"
"An array stores a collection of values.\n"
"A variable stores a value.\n"
"A function is reusable code that performs a task.\n"
"A loop repeats instructions.\n"
"A conditional lets a program choose between paths.\n"
"A pointer stores a memory address.\n"
"A buffer is an area of memory used to hold data temporarily.\n"
"An operating system manages hardware and provides services to programs.\n"
"A kernel is the core part of an operating system.\n"
"A scheduler selects tasks for execution.\n"
"An interrupt requests attention from a processor.\n"
"Input provides information to a program.\n"
"Output is information produced by a program.\n"
"An API allows software components to communicate.\n"
"A local program can operate without contacting a remote server.\n"
"An offline system does not require an internet connection for its main operation.\n"
"Artificial intelligence is a broad field involving systems that perform tasks associated with intelligent behavior.\n"
"Machine learning uses data and algorithms to learn patterns.\n"
"A language model models patterns in sequences of language.\n"
"A neural network is a computational model made from interconnected units.\n"
"A transformer is a neural network architecture used by many modern language models.\n"
"Not every language model is a neural network.\n"
"An n-gram model uses sequences of tokens or words to model local language patterns.\n"
"Small models can be useful when resources are limited.\n"
"Resource constraints influence software design.\n"
"Memory usage is important on small computers.\n"
"Processing speed is important for interactive systems.\n"
"Latency is the delay between input and response.\n"
"A benchmark measures performance under defined conditions.\n"
"Efficient algorithms can reduce computation and memory use.\n"
"Good software starts with a clear problem.\n"
"Clear requirements make implementation easier.\n"
"Testing helps verify whether software behaves correctly.\n"
"Debugging helps locate unexpected behavior.\n"
"Version control helps track changes to software.\n"
"A repository can contain source code and project files.\n"
"Documentation explains how a project works.\n"
"Comments can explain why code exists.\n"
"Readable code is easier to maintain.\n"
"Modular code separates a large problem into smaller pieces.\n"
"Interfaces define how components communicate.\n"
"Abstraction allows programmers to work with concepts without handling every detail at once.\n"
"Optimization should target actual bottlenecks.\n"
"Measuring performance is usually better than guessing about performance.\n"
"Memory leaks can cause a program to consume memory over time.\n"
"Stack memory is commonly used for function calls and local variables.\n"
"Heap memory can be allocated dynamically.\n"
"An error message can provide useful debugging information.\n"
"A log records information about program behavior.\n"
"A serial terminal can display debugging output from embedded hardware.\n"

"@@section embedded\n"
"An embedded system is a computer designed for a specific purpose.\n"
"A microcontroller combines a processor with memory and peripherals.\n"
"The ESP32 is a family of microcontrollers designed for embedded applications.\n"
"The ESP32-S3 is a member of the ESP32 family.\n"
"GPIO pins can be configured for digital input and output.\n"
"UART is a serial communication interface.\n"
"SPI is a synchronous serial communication interface.\n"
"I2C is a two-wire serial communication interface.\n"
"A timer can measure time or generate periodic events.\n"
"An interrupt can notify software about a hardware event.\n"
"Firmware is software associated with hardware.\n"
"Flash memory can store firmware.\n"
"RAM is used while a program is running.\n"
"Some microcontrollers provide additional memory such as PSRAM.\n"
"Embedded systems often have stricter memory limits than desktop computers.\n"
"Power consumption can be important in embedded devices.\n"
"Microcontrollers are commonly used in sensors and controllers.\n"
"An ESP32 can communicate with peripherals using interfaces such as SPI and I2C.\n"
"Embedded programming often requires careful management of memory and timing.\n"
"Small hardware can run useful software when the software is designed for the hardware.\n"
"An embedded language model must account for available memory and processing power.\n"
"Serial communication is useful for debugging embedded systems.\n"
"Memory constraints can strongly influence embedded software design.\n"
"Timing can matter when software interacts with hardware.\n"
"Hardware registers can provide direct access to peripheral functionality.\n"
"Direct hardware access requires careful programming.\n"
"Embedded software often runs continuously.\n"
"A firmware update can change the behavior of an embedded device.\n"
"A bootloader can load or start firmware.\n"
"Embedded systems can be found in appliances, vehicles, sensors, controllers, and many other devices.\n"
"Small processors can perform useful tasks without a desktop computer.\n"
"An ESP32 can run networking, control, sensing, and other applications.\n"
"An ESP32-S3 can run local software without requiring a cloud service.\n"
"Running an AI system on a microcontroller requires careful resource management.\n"
"Flash can store model data while RAM holds active working data.\n"
"PSRAM can provide additional memory for systems that support it.\n"
"Serial output is useful when developing firmware.\n"
"Stress testing can reveal memory and timing problems.\n"
"Resetting a microcontroller restarts its firmware.\n"
"Persistent storage can preserve configuration across resets.\n"

"@@section science\n"
"Science uses observation, evidence, testing, and reasoning to study the natural world.\n"
"Physics studies matter, energy, motion, forces, and interactions.\n"
"Chemistry studies matter and the changes it undergoes.\n"
"Biology studies living organisms.\n"
"An experiment tests an idea under controlled conditions.\n"
"A hypothesis is a testable proposed explanation.\n"
"Evidence is information used to support or evaluate an explanation.\n"
"A measurement assigns a value to a property.\n"
"Units describe what a measurement represents.\n"
"Energy is the ability to cause change or do work.\n"
"Force can change the motion of an object.\n"
"Gravity is an interaction associated with mass.\n"
"Motion describes a change in position over time.\n"
"Temperature describes the thermal state of matter.\n"
"Matter has mass and occupies space.\n"
"Atoms are basic units of ordinary matter.\n"
"Molecules are made from atoms joined by chemical bonds.\n"
"Cells are basic units of living organisms.\n"
"Plants use photosynthesis to convert light energy into chemical energy.\n"
"The Earth is a planet that orbits the Sun.\n"
"The Moon orbits Earth.\n"
"Science depends on evidence rather than simply assuming an answer.\n"
"Repeating measurements can improve confidence in experimental results.\n"
"A scientific explanation should be consistent with available evidence.\n"
"Observation is an important part of science.\n"
"Scientists use evidence to evaluate explanations.\n"
"Controlled experiments can help isolate variables.\n"
"A variable is something that can change in an experiment.\n"
"Data can be collected through observation and measurement.\n"
"Graphs can help display scientific data.\n"
"Scientific models can represent systems or processes.\n"
"Good scientific questions can be tested using evidence.\n"

"@@section ela\n"
"A noun names a person, place, thing, or idea.\n"
"A pronoun can replace a noun.\n"
"A verb expresses an action or state of being.\n"
"An adjective describes or modifies a noun.\n"
"An adverb can modify a verb, adjective, or another adverb.\n"
"A preposition shows a relationship between words.\n"
"A conjunction connects words or groups of words.\n"
"An interjection expresses a feeling or reaction.\n"
"A sentence normally expresses a complete thought.\n"
"A subject tells who or what a sentence is about.\n"
"A predicate tells what the subject does or is.\n"
"A paragraph usually develops a central idea.\n"
"The main idea is the most important point of a passage.\n"
"Supporting details explain or support the main idea.\n"
"A theme is an idea or message explored by a literary work.\n"
"A character is a person, animal, or figure in a story.\n"
"Setting describes when and where a story takes place.\n"
"Plot describes the sequence of events in a story.\n"
"Conflict is a problem or struggle in a story.\n"
"Point of view describes the perspective from which a story is told.\n"
"First person uses words such as I and we.\n"
"Third person uses words such as he, she, they, or names.\n"
"A metaphor compares unlike things without using like or as.\n"
"A simile makes a comparison using like or as.\n"
"Personification gives human qualities to something nonhuman.\n"
"Context can help determine the meaning of an unfamiliar word.\n"
"A synonym is a word with a similar meaning.\n"
"An antonym is a word with an opposite meaning.\n"
"An inference is a conclusion supported by evidence and reasoning.\n"
"A summary gives the main information from a text.\n"
"Evidence supports a claim or interpretation.\n"
"An essay usually contains an introduction, body paragraphs, and a conclusion.\n"
"A thesis states the main idea or argument of an essay.\n"
"Revision improves the content and organization of writing.\n"
"Proofreading checks writing for errors.\n"
"Clear writing communicates ideas efficiently.\n"
"Good word choice can make writing more precise.\n"
"Grammar describes rules and patterns used in language.\n"
"Punctuation helps organize written language.\n"
"Writing can be revised several times.\n"
"Different word choices can change tone.\n"
"Context can change how a sentence is interpreted.\n"
"Dialogue can reveal information about characters.\n"
"Description can help a reader imagine a setting.\n"
"A strong paragraph usually stays focused on one main idea.\n"
"Evidence should be relevant to the claim it supports.\n"
"A conclusion can reinforce the main idea of a piece of writing.\n"

"@@section social_studies\n"
"Social studies examines people, societies, history, geography, government, and economics.\n"
"History studies events and developments from the past.\n"
"Geography studies places, people, environments, and relationships between them.\n"
"Government is a system used to organize and govern a society.\n"
"A democracy is a system in which political power is connected to the people.\n"
"A constitution establishes fundamental rules and structures for a government.\n"
"Laws are rules created and enforced by a government.\n"
"Citizens have rights and responsibilities.\n"
"Economics studies how people and societies use limited resources.\n"
"Supply describes how much of something producers are willing to provide.\n"
"Demand describes how much of something consumers are willing to buy.\n"
"Resources can be limited.\n"
"Trade involves exchanging goods or services.\n"
"Culture includes shared practices, ideas, traditions, and values.\n"
"Primary sources come directly from the time or event being studied.\n"
"Secondary sources interpret or analyze information about the past.\n"
"A timeline organizes events in chronological order.\n"
"Chronological means arranged according to time.\n"
"Maps represent geographic information.\n"
"Latitude measures position north or south of the Equator.\n"
"Longitude measures position east or west of the Prime Meridian.\n"
"Historical evidence can include documents, objects, photographs, and firsthand accounts.\n"
"Historical claims should be supported by evidence.\n"
"Different sources can provide different perspectives on the same event.\n"
"Comparing sources can reveal similarities and differences.\n"
"Cause explains why something happened.\n"
"Effect describes what happened as a result.\n"
"Historical events often have multiple causes and effects.\n"
"Understanding context helps explain historical events.\n"
"Geography can influence how societies develop.\n"
"Maps can represent physical and human features.\n"
"Historical interpretation depends on available evidence.\n"
"Sources should be evaluated carefully.\n"

"@@section language_model\n"
"A language model predicts or scores sequences of language.\n"
"An n-gram is a sequence of n items.\n"
"A unigram contains one item.\n"
"A bigram contains two items.\n"
"A trigram contains three items.\n"
"A higher-order n-gram uses more context.\n"
"An n-gram model estimates how likely a token is given previous tokens.\n"
"A corpus is a collection of text used by a language system.\n"
"The corpus strongly influences the language patterns an n-gram model can generate.\n"
"A focused corpus can make a small language model more useful for a specific task.\n"
"Tokenization converts text into units that a language model can process.\n"
"Context is the previous language available to the model.\n"
"Sampling selects an outcome from possible candidates.\n"
"Temperature can change how random sampling behaves.\n"
"A higher temperature generally allows more variation.\n"
"A lower temperature generally favors more likely choices.\n"
"Language generation repeatedly chooses what should come next.\n"
"An n-gram model is fundamentally different from a transformer language model.\n"
"A transformer uses neural network layers and learned parameters.\n"
"An n-gram model relies on observed local sequences and their statistics.\n"
"A small language model can run on constrained hardware.\n"
"Memory usage is an important constraint for microcontroller language models.\n"
"Flash can store a corpus while RAM can hold active runtime data.\n"
"Local inference means the model runs on the device performing the interaction.\n"
"An offline language model does not need a cloud service for inference.\n"
"An API can provide access to a remote model, but an API is not required for every language model.\n"
"Espie is designed as a local n-gram language model and AI assistant.\n"
"Espie's corpus provides examples of language for local generation.\n"
"Espie's factual knowledge can be separated from generated language.\n"
"A language model can generate plausible text without guaranteeing that every generated statement is factual.\n"
"Factual retrieval and free generation are different tasks.\n"
"A good assistant can use different mechanisms for different kinds of input.\n"
"Conversation benefits from a corpus containing natural conversational language.\n"
"A language model trained on technical text will tend to reproduce technical language.\n"
"A language model trained on conversational text will have more conversational patterns available.\n"
"Corpus design is part of language-model design.\n"
"More conversational examples give a model more conversational patterns to work with.\n"
"Repeated phrases can become strong patterns in an n-gram model.\n"
"Context length affects how much previous text influences generation.\n"
"Generation can be affected by both context and sampling.\n"
"Random seeds can make sampling reproducible.\n"
"Changing the seed can produce a different sampled continuation.\n"
"Changing temperature can change the variety of generated output.\n"
"Changing corpus content can change which continuations are available.\n"
"Routing can focus generation on a relevant part of a corpus.\n"
"Factual answers can use a separate verified knowledge store.\n"
"Free generation can produce text that is plausible without being verified.\n"
"A language model is only as useful as the patterns and mechanisms available to it.\n"
"Testing a language model with many prompts can reveal unusual behavior.\n"
"Stress testing can reveal edge cases.\n"
"Unexpected output can reveal weaknesses in a corpus or generation system.\n"
"An n-gram model can be surprisingly capable when given useful text.\n"
"Small models can be interesting engineering projects.\n"
"Resource limits can make optimization necessary.\n"
"Running a model locally can reduce dependence on external services.\n"
"Offline AI can be useful when connectivity is unavailable.\n"
"Local models can expose their internals more directly than cloud services.\n"
"Debug traces can help developers understand model behavior.\n"
"Model behavior can depend heavily on the training corpus.\n"
"Training data quality matters.\n"
"Training data organization matters.\n"
"Conversational data should contain natural conversational patterns.\n"
"Technical data should contain accurate technical statements.\n"
"A mixture of domains can make a model more versatile.\n"
"Domain routing can reduce irrelevant generation.\n"
"Conversation history can provide useful context.\n"
"Longer context is not always better if irrelevant text is included.\n"
"Good routing can help a small model focus on useful text.\n"
"Good corpus design and good inference logic work together.\n"
"That combination can make a small model much more useful.\n";

const char TRAIN_FACTS[] PROGMEM =

"espie~Espie is a local n-gram language model and AI assistant designed to run on an ESP32-S3.\n"
"esp32~The ESP32 is a family of microcontrollers designed for embedded applications.\n"
"esp32-s3~The ESP32-S3 is a member of Espressif's ESP32 family of microcontrollers and uses a dual-core Xtensa LX7 processor.\n"
"ram~RAM is memory used to hold data that a computer is actively using.\n"
"flash~Flash memory is nonvolatile memory that retains stored data without power.\n"
"psram~PSRAM is external pseudo-static RAM used by some embedded systems to provide additional memory.\n"
"uart~UART is an asynchronous serial communication interface.\n"
"spi~SPI is a synchronous serial communication interface commonly used to connect peripherals.\n"
"i2c~I2C is a two-wire serial communication interface commonly used to connect peripherals.\n"
"gpio~GPIO stands for general-purpose input/output and refers to configurable digital pins.\n"
"kernel~A kernel is the core software component of an operating system that manages hardware and system resources.\n"
"scheduler~A scheduler selects tasks or processes for execution.\n"
"filesystem~A filesystem organizes data into files and directories.\n"
"compiler~A compiler translates source code into another representation, commonly machine code or object code.\n"
"linker~A linker combines program components and resolves references between them.\n"
"pointer~A pointer stores a memory address.\n"
"buffer~A buffer is a region of memory used to temporarily hold data.\n"
"interrupt~An interrupt is a signal that requests attention from a processor.\n"
"timer~A timer measures elapsed time or generates events at specified intervals.\n"
"language model~A language model assigns probabilities or scores to sequences of language and can be used to generate text.\n"
"n-gram~An n-gram is a sequence of n items, such as words or tokens.\n"
"corpus~A corpus is a collection of text used for language analysis or model training.\n"
"temperature~Temperature is a sampling parameter that can affect the randomness of generated output.\n"
"sampling~Sampling selects an outcome from a set of possible outcomes according to probabilities or scores.\n"
"noun~A noun is a word that names a person, place, thing, or idea.\n"
"verb~A verb expresses an action or state of being.\n"
"adjective~An adjective modifies or describes a noun.\n"
"adverb~An adverb can modify a verb, adjective, or another adverb.\n"
"democracy~Democracy is a form of government in which political authority is connected to the people.\n"
"latitude~Latitude measures angular position north or south of the Equator.\n"
"longitude~Longitude measures angular position east or west of the Prime Meridian.\n"
"triangle~A triangle is a polygon with three sides.\n"
"rectangle~A rectangle is a quadrilateral with four right angles.\n"
"circle~A circle is the set of points in a plane that are a given distance from a center point.\n"
"photosynthesis~Photosynthesis is the process by which plants and other organisms convert light energy into chemical energy.\n"
"gravity~Gravity is an interaction associated with mass that causes attraction between masses.\n"
"atom~An atom is the basic unit of an element that retains the chemical identity of that element.\n"
"cell~A cell is the basic structural and functional unit of living organisms.\n"
"nctc~NCTC is the competition where Espie's demonstration can be presented to judges.\n";

const char TRAIN_EXAMPLES[] PROGMEM =

"greeting~hi hello hey hello there hi there good morning good afternoon good evening morning hey there hello again\n"
"farewell~goodbye bye see you see you later see you soon good night take care talk to you later\n"
"gratitude~thanks thank you appreciate appreciated grateful that helps thanks for explaining\n"
"agreement~yes correct exactly right agree makes sense that is right good point definitely absolutely\n"
"positive~good great nice cool awesome interesting excellent perfect wonderful sounds good sounds great\n"
"confusion~confused unclear do not understand what mean explain simpler confused about this not sure\n"
"conversation~hello hi hey how are you how are you doing what are you doing how is your day what is going on tell me more\n"
"feelings~happy sad excited worried nervous frustrated confused curious proud surprised funny laughing fun\n"
"manners~please thank thanks sorry excuse me appreciate welcome no problem you are welcome patience\n"
"espie~espie ai assistant local offline ngram personality girl smart friendly corpus model embedded\n"
"nctc~nctc judges competition demonstration espie judges hello\n"
"school~school class teacher homework assignment project studying test quiz grade student lesson notes essay presentation research\n"
"technology~computer software hardware program code compiler debugger algorithm processor memory operating system application technology\n"
"embedded~esp32 microcontroller gpio uart spi i2c firmware embedded hardware sensor timer flash psram\n"
"science~science physics chemistry biology experiment hypothesis evidence energy force matter atom cell planet gravity\n"
"ela~english language noun verb adjective adverb paragraph essay grammar punctuation theme character setting metaphor simile summary\n"
"social_studies~history geography government democracy constitution law citizen economics supply demand culture map timeline evidence\n"
"language_model~language model ngram corpus token context sampling temperature generation probability text assistant inference\n"
"programming~code program function variable array loop pointer compiler source debugging bug error test memory\n"
"debugging~bug error crash fault failure debug problem test fix issue output input behavior\n"
"learning~learn study practice understand explain example lesson school knowledge skill improve\n"
"help~help explain tell show understand assist guide example simpler step by step\n"
"opinion~think believe prefer like dislike interesting useful cool idea approach\n"
"stress_test~stress test testing experiment bug edge case unexpected reproduce investigate debug benchmark\n"
"project~project build create make run test improve design engineering hardware software\n";

const char TRAIN_PROPER[] PROGMEM =

"ESP32\n"
"ESP32-S3\n"
"ESP32-C3\n"
"ESP32-S2\n"
"Arduino\n"
"Espressif\n"
"C\n"
"C++\n"
"Python\n"
"UART\n"
"SPI\n"
"I2C\n"
"GPIO\n"
"RAM\n"
"ROM\n"
"EEPROM\n"
"PSRAM\n"
"CPU\n"
"AI\n"
"MegaLM\n"
"Espie\n"
"School\n"
"English\n"
"Science\n"
"History\n"
"Arduino IDE\n"
"Wokwi\n";

const char TRAIN_WORDS[] PROGMEM =

"hi\n"
"hello\n"
"hey\n"
"there\n"
"again\n"
"good\n"
"great\n"
"nice\n"
"cool\n"
"awesome\n"
"interesting\n"
"okay\n"
"alright\n"
"sure\n"
"yes\n"
"no\n"
"maybe\n"
"thanks\n"
"thank\n"
"please\n"
"welcome\n"
"help\n"
"explain\n"
"understand\n"
"mean\n"
"think\n"
"know\n"
"guess\n"
"tell\n"
"show\n"
"give\n"
"example\n"
"simple\n"
"easy\n"
"hard\n"
"complex\n"
"problem\n"
"answer\n"
"idea\n"
"thing\n"
"way\n"
"part\n"
"reason\n"
"because\n"
"school\n"
"class\n"
"teacher\n"
"student\n"
"homework\n"
"assignment\n"
"project\n"
"test\n"
"quiz\n"
"study\n"
"learn\n"
"lesson\n"
"subject\n"
"grade\n"
"computer\n"
"technology\n"
"software\n"
"hardware\n"
"program\n"
"programming\n"
"code\n"
"compiler\n"
"debugger\n"
"debug\n"
"bug\n"
"algorithm\n"
"function\n"
"array\n"
"loop\n"
"pointer\n"
"memory\n"
"processor\n"
"cpu\n"
"operating\n"
"system\n"
"kernel\n"
"file\n"
"filesystem\n"
"directory\n"
"application\n"
"science\n"
"physics\n"
"chemistry\n"
"biology\n"
"experiment\n"
"energy\n"
"force\n"
"matter\n"
"atom\n"
"cell\n"
"planet\n"
"gravity\n"
"english\n"
"language\n"
"noun\n"
"verb\n"
"adjective\n"
"adverb\n"
"pronoun\n"
"paragraph\n"
"essay\n"
"grammar\n"
"punctuation\n"
"theme\n"
"character\n"
"setting\n"
"metaphor\n"
"simile\n"
"summary\n"
"history\n"
"geography\n"
"government\n"
"democracy\n"
"constitution\n"
"law\n"
"citizen\n"
"economics\n"
"supply\n"
"demand\n"
"culture\n"
"map\n"
"timeline\n"
"evidence\n"
"embedded\n"
"esp32\n"
"microcontroller\n"
"gpio\n"
"uart\n"
"spi\n"
"i2c\n"
"firmware\n"
"sensor\n"
"timer\n"
"flash\n"
"psram\n"
"model\n"
"ngram\n"
"corpus\n"
"token\n"
"context\n"
"sampling\n"
"temperature\n"
"generation\n"
"probability\n"
"response\n"
"conversation\n"
"assistant\n"
"inference\n"
"local\n"
"offline\n"
"fast\n"
"useful\n"
"small\n"
"friendly\n"
"smart\n"
"curious\n"
"happy\n"
"excited\n"
"confused\n"
"frustrated\n"
"proud\n"
"surprised\n"
"funny\n"
"fun\n"
"manners\n"
"please\n"
"sorry\n"
"excuse\n"
"welcome\n"
"patience\n"
"judges\n"
"nctc\n"
"competition\n"
"demonstration\n"
"project\n"
"build\n"
"create\n"
"make\n"
"run\n"
"read\n"
"write\n"
"learn\n"
"remember\n"
"real\n"
"test\n"
"testing\n"
"stress\n"
"debug\n"
"experiment\n"
"investigate\n"
"reproduce\n"
"result\n"
"behavior\n"
"output\n"
"input\n"
"design\n"
"engineering\n"
"system\n"
"device\n"
"hardware\n"
"firmware\n"
"local\n"
"model\n"
"language\n"
"pattern\n"
"patterns\n"
"sentence\n"
"word\n"
"words\n"
"question\n"
"answer\n"
"conversation\n"
"talk\n"
"talking\n"
"feel\n"
"feeling\n"
"feelings\n"
"day\n"
"today\n"
"morning\n"
"afternoon\n"
"evening\n"
"night\n"
"hello\n"
"goodbye\n"
"later\n"
"soon\n"
"thanks\n"
"appreciate\n"
"kind\n"
"nice\n"
"helpful\n"
"interesting\n"
"exciting\n"
"awesome\n"
"amazing\n"
"great\n"
"perfect\n"
"fine\n"
"well\n"
"okay\n"
"alright\n"
"certain\n"
"uncertain\n"
"guess\n"
"fact\n"
"facts\n"
"knowledge\n"
"verified\n"
"unknown\n"
"information\n"
"context\n"
"topic\n"
"section\n"
"raw\n"
"seed\n"
"order\n"
"length\n"
"temp\n"
"think\n"
"stats\n"
"bench\n"
"help\n";

#endif
